import { ACUnit, SubscriptionPlan, ManagerAccount, UserAccount, Organization, Venue } from './types';

export const mockPlans: SubscriptionPlan[] = [
  {
    id: 'plan-basic',
    name: 'Basic',
    maxOrgs: 1,
    maxVenues: 2,
    maxDevices: 10,
    reportVisibility: ['daily', 'monthly'],
  },
  {
    id: 'plan-pro',
    name: 'Pro',
    maxOrgs: 5,
    maxVenues: 10,
    maxDevices: 50,
    reportVisibility: ['hourly', 'daily', 'weekly', 'monthly', 'yearly'],
  },
];

export const mockManagers: ManagerAccount[] = [
  {
    id: 'mgr-1',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    status: 'active',
    planId: 'plan-pro',
  },
];

export const mockUsers: UserAccount[] = [
  {
    id: 'usr-1',
    name: 'Bob Smith',
    email: 'bob@example.com',
    status: 'active',
    assignedVenueIds: ['ven-1', 'ven-2'],
    managerId: 'mgr-1',
    subscriptionType: 'Premium',
  },
];

export const mockOrgs: Organization[] = [
  { 
    id: 'org-1', 
    name: 'SSUET_AS', 
    managerId: 'mgr-1',
    address: 'SSUET Campus, University Road, Karachi',
  },
  { 
    id: 'org-2', 
    name: 'IoTFIY_HQ', 
    managerId: 'mgr-1',
    address: 'IoTFIY Innovation Hub, Block 4, Karachi',
  },
];

export const mockVenues: Venue[] = [
  { id: 'ven-1', name: 'SSUET_AF', orgId: 'org-1' },
  { id: 'ven-2', name: 'SSUET_CF', orgId: 'org-1' },
  { id: 'ven-3', name: 'SSUET_BS', orgId: 'org-1' },
  { id: 'ven-4', name: 'SSUET_DT', orgId: 'org-1' },
  { id: 'ven-5', name: 'SSUET_GS', orgId: 'org-1' },
  { id: 'ven-6', name: 'HQ_Lobby', orgId: 'org-2' },
  { id: 'ven-7', name: 'HQ_ServerRoom', orgId: 'org-2' },
  { id: 'ven-8', name: 'HQ_RD_Lab', orgId: 'org-2' },
];

export const mockACUnits: ACUnit[] = [
  {
    id: 'ac-001',
    name: 'AF-101 Seminar Hall',
    venueId: 'ven-1',
    isOn: true,
    currentTemp: 26,
    targetTemp: 26,
    isLocked: false,
    eventLocked: false,
    hasFault: false,
    energyConsumption: {
      hourly: [
        { label: '08:00', kwh: 1.2 },
        { label: '09:00', kwh: 1.5 },
        { label: '10:00', kwh: 1.8 },
        { label: '11:00', kwh: 1.4 },
        { label: '12:00', kwh: 1.6 },
      ],
      daily: [
        { label: 'Mon', kwh: 15 },
        { label: 'Tue', kwh: 18 },
        { label: 'Wed', kwh: 14 },
        { label: 'Thu', kwh: 16 },
        { label: 'Fri', kwh: 19 },
        { label: 'Sat', kwh: 5 },
        { label: 'Sun', kwh: 4 },
      ],
      weekly: [
        { label: 'Week 1', kwh: 105 },
        { label: 'Week 2', kwh: 112 },
        { label: 'Week 3', kwh: 98 },
        { label: 'Week 4', kwh: 135 },
      ],
      monthly: [
        { label: 'Jan', kwh: 450 },
        { label: 'Feb', kwh: 420 },
        { label: 'Mar', kwh: 480 },
        { label: 'Apr', kwh: 510 },
        { label: 'May', kwh: 600 },
        { label: 'Jun', kwh: 750 },
      ],
      yearly: [
        { label: '2021', kwh: 5200 },
        { label: '2022', kwh: 5400 },
        { label: '2023', kwh: 5100 },
        { label: '2024', kwh: 5300 },
      ],
    },
    events: [
      {
        id: 'evt-1',
        name: 'Morning Cool',
        time: '08:00',
        action: 'ON',
        targetTemp: 22,
        isRecurring: true,
        days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        enabled: true,
      },
      {
        id: 'evt-2',
        name: 'Evening Off',
        time: '18:00',
        action: 'OFF',
        isRecurring: true,
        days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        enabled: true,
      },
    ],
  },
  {
    id: 'ac-002',
    name: 'AF-102 Class Room',
    venueId: 'ven-1',
    isOn: true,
    currentTemp: 26,
    targetTemp: 26,
    isLocked: false,
    eventLocked: false,
    hasFault: false,
    energyConsumption: {
      hourly: [
        { label: '08:00', kwh: 1.0 },
        { label: '09:00', kwh: 1.2 },
        { label: '10:00', kwh: 1.4 },
        { label: '11:00', kwh: 1.1 },
        { label: '12:00', kwh: 1.3 },
      ],
      daily: [
        { label: 'Mon', kwh: 12 },
        { label: 'Tue', kwh: 14 },
        { label: 'Wed', kwh: 11 },
        { label: 'Thu', kwh: 13 },
        { label: 'Fri', kwh: 15 },
        { label: 'Sat', kwh: 2 },
        { label: 'Sun', kwh: 1 },
      ],
      weekly: [
        { label: 'Week 1', kwh: 80 },
        { label: 'Week 2', kwh: 85 },
        { label: 'Week 3', kwh: 78 },
        { label: 'Week 4', kwh: 90 },
      ],
      monthly: [
        { label: 'Jan', kwh: 350 },
        { label: 'Feb', kwh: 320 },
        { label: 'Mar', kwh: 360 },
        { label: 'Apr', kwh: 380 },
        { label: 'May', kwh: 420 },
        { label: 'Jun', kwh: 490 },
      ],
      yearly: [
        { label: '2021', kwh: 4000 },
        { label: '2022', kwh: 4200 },
        { label: '2023', kwh: 4100 },
        { label: '2024', kwh: 4300 },
      ],
    },
    events: [],
  },
  {
    id: 'ac-003',
    name: 'CF-201 Computer Lab',
    venueId: 'ven-2',
    isOn: true,
    currentTemp: 24,
    targetTemp: 24,
    isLocked: false,
    eventLocked: false,
    hasFault: false,
    energyConsumption: {
      hourly: [{ label: '08:00', kwh: 2.2 }, { label: '09:00', kwh: 2.5 }],
      daily: [{ label: 'Mon', kwh: 22 }, { label: 'Tue', kwh: 25 }],
      weekly: [{ label: 'Week 1', kwh: 150 }],
      monthly: [{ label: 'Jan', kwh: 620 }],
      yearly: [{ label: '2024', kwh: 7500 }],
    },
    events: [],
  },
  {
    id: 'ac-004',
    name: 'CF-202 Chemistry Lab',
    venueId: 'ven-2',
    isOn: false,
    currentTemp: 27,
    targetTemp: 25,
    isLocked: true,
    eventLocked: false,
    hasFault: false,
    energyConsumption: {
      hourly: [{ label: '08:00', kwh: 0.8 }],
      daily: [{ label: 'Mon', kwh: 8 }],
      weekly: [{ label: 'Week 1', kwh: 56 }],
      monthly: [{ label: 'Jan', kwh: 240 }],
      yearly: [{ label: '2024', kwh: 2900 }],
    },
    events: [],
  },
  {
    id: 'ac-005',
    name: 'BS-301 Biology Lab',
    venueId: 'ven-3',
    isOn: false,
    currentTemp: 28,
    targetTemp: 26,
    isLocked: false,
    eventLocked: false,
    hasFault: true,
    energyConsumption: {
      hourly: [{ label: '08:00', kwh: 1.1 }],
      daily: [{ label: 'Mon', kwh: 12 }],
      weekly: [{ label: 'Week 1', kwh: 84 }],
      monthly: [{ label: 'Jan', kwh: 360 }],
      yearly: [{ label: '2024', kwh: 4100 }],
    },
    events: [],
  },
  {
    id: 'ac-006',
    name: 'DT-401 Lecture Theater',
    venueId: 'ven-4',
    isOn: false,
    currentTemp: 30,
    targetTemp: 30,
    isLocked: false,
    eventLocked: false,
    hasFault: false,
    energyConsumption: {
      hourly: [{ label: '08:00', kwh: 4.1 }],
      daily: [{ label: 'Mon', kwh: 45 }],
      weekly: [{ label: 'Week 1', kwh: 315 }],
      monthly: [{ label: 'Jan', kwh: 1350 }],
      yearly: [{ label: '2024', kwh: 16200 }],
    },
    events: [],
  },
  {
    id: 'ac-007',
    name: 'GS-501 Physics Lab',
    venueId: 'ven-5',
    isOn: true,
    currentTemp: 28,
    targetTemp: 28,
    isLocked: true,
    eventLocked: false,
    hasFault: false,
    energyConsumption: {
      hourly: [{ label: '08:00', kwh: 1.3 }],
      daily: [{ label: 'Mon', kwh: 14 }],
      weekly: [{ label: 'Week 1', kwh: 98 }],
      monthly: [{ label: 'Jan', kwh: 420 }],
      yearly: [{ label: '2024', kwh: 5040 }],
    },
    events: [],
  },
  {
    id: 'ac-008',
    name: 'AF-103 Faculty Office',
    venueId: 'ven-1',
    isOn: false,
    currentTemp: 26,
    targetTemp: 24,
    isLocked: false,
    eventLocked: false,
    hasFault: true,
    energyConsumption: {
      hourly: [{ label: '08:00', kwh: 0.5 }],
      daily: [{ label: 'Mon', kwh: 5 }],
      weekly: [{ label: 'Week 1', kwh: 35 }],
      monthly: [{ label: 'Jan', kwh: 150 }],
      yearly: [{ label: '2024', kwh: 1800 }],
    },
    events: [],
  },
  {
    id: 'ac-009',
    name: 'HQ-101 Main Reception',
    venueId: 'ven-6',
    isOn: true,
    currentTemp: 23,
    targetTemp: 22,
    isLocked: false,
    eventLocked: false,
    hasFault: false,
    energyConsumption: {
      hourly: [{ label: '08:00', kwh: 1.5 }],
      daily: [{ label: 'Mon', kwh: 18 }],
      weekly: [{ label: 'Week 1', kwh: 126 }],
      monthly: [{ label: 'Jan', kwh: 540 }],
      yearly: [{ label: '2024', kwh: 6480 }],
    },
    events: [],
  },
  {
    id: 'ac-010',
    name: 'HQ Server Rack A',
    venueId: 'ven-7',
    isOn: true,
    currentTemp: 18,
    targetTemp: 18,
    isLocked: true,
    eventLocked: false,
    hasFault: false,
    energyConsumption: {
      hourly: [{ label: '08:00', kwh: 2.2 }],
      daily: [{ label: 'Mon', kwh: 52 }],
      weekly: [{ label: 'Week 1', kwh: 364 }],
      monthly: [{ label: 'Jan', kwh: 1560 }],
      yearly: [{ label: '2024', kwh: 18720 }],
    },
    events: [],
  },
  {
    id: 'ac-011',
    name: 'HQ-201 Dev Space',
    venueId: 'ven-8',
    isOn: true,
    currentTemp: 24,
    targetTemp: 23,
    isLocked: false,
    eventLocked: false,
    hasFault: false,
    energyConsumption: {
      hourly: [{ label: '08:00', kwh: 1.8 }],
      daily: [{ label: 'Mon', kwh: 22 }],
      weekly: [{ label: 'Week 1', kwh: 154 }],
      monthly: [{ label: 'Jan', kwh: 660 }],
      yearly: [{ label: '2024', kwh: 7920 }],
    },
    events: [],
  }
];
